---
title: "R. Bruel > Publications"
#author: "Rosalie Bruel"
#date: "19/02/2019"
lang: "en"
output: html_document
---

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134870808-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-134870808-1');
</script>

<style>
# space between paragraph, small or big
p.small {
  line-height: 0.7;
}
p.big {
  line-height: 1.8;
}

p {
  text-indent: 1.5em;
}

.first {
  text-indent: 2em;
}

.second {
  text-indent: -2.5em;
}

.title{
    display: none;
}

/* Color for links */
a:link {
  color: #2a5d9f; /* cobalt blue */
  background-color: transparent;
  text-decoration: none;
}

a:visited {
  color: #2a5d9f; /* cobalt blue */
  background-color: transparent;
  text-decoration: none;
}

a:hover {
  color: #1a3c66; /* darker blue on hover */
  background-color: transparent;
  text-decoration: underline;
}

a:active {
  color: #274472; /* rich, slightly muted blue */
  background-color: transparent;
  text-decoration: underline;
}
/* end color for links */

</style>


***  


### Publications
***

<br>

<head><b>Publications</b> (last updated on `r paste(month.name[as.numeric(paste(format(Sys.Date(), format = "%m")))], format(Sys.Date(), format = "%d, %Y"))`. See also my <a href="https://orcid.org/0000-0001-8351-7539" target="_blank">ORCID profile</a>):</head>


<ol reversed>


<br>
<p class="second"><u>2025</u></p>
<li>Vagnon, C., Chevalier, M., Boulêtreau, S., <b>Bruel, R.</b>, Guillon, S., Holtgrieve, G., et al. (2025). Experimental Evidence for the Desynchronization of Ecosystem Dynamics by Global Change. _Ecology Letters_ 28, e70271. https://doi.org/10.1111/ele.70271

<li>Dory, F., Arthaud, F., Augé, V., Baillot, S., Bertrand, C., Birck, C., <b>Bruel, R.</b>, Cavalli, L., Franquet, E., Jacob, F., Sagot, C., Souchier, M., Napoleoni, R., Perga, M.-É. 2025. Vulnerable but not equal: mountain lakes exhibit heterogeneous patterns of phytoplankton responses to climate change. _Limnology and Oceanography Letters_. DOI: <a href="https://aslopubs.onlinelibrary.wiley.com/doi/10.1002/lol2.70034" target="_blank">DOI: 10.1002/lol2.70034</a>

<li>Tran-Khac, V., Doubek, J.P., Patil, V., Stockwell, J.D., Adrian, R., Chang, C.-W., Dur, G., Lewandowska, A., Rusak, J.A., Salmaso, N., Straile, D., Thackeray, S.J., Venail, P., Bhattacharya, R., Brentrup, J., <b>Bruel, R.</b>, Feuchtmayr, H., Gessner, M.O., Grossart, H.-P., Ibelings, B.W., Jacquet, S., MacIntyre, S., Matsuzaki, S.-I.S., Nodine, E., Nõges, P., Rudstam, L., Soulignac, F., Verburg, P., Znachor, P., Zohary, T., Anneville, O., 2025. Using Long-Term Ecological Datasets to Unravel the Impacts of Short-Term Meteorological Disturbances on Phytoplankton Communities. _Freshwater Biology_ <b>70</b>, e70023. <a href="https://doi.org/10.1111/fwb.70023" target="_blank">DOI: 10.1111/fwb.70023</a>


<li>Leclerc, C., Frossard, V., Sharaf, N., Bazin, S., <b>Bruel, R.</b>, Sentis, A. 2025. Climate Impacts on Lake Food-Webs Are Mediated by Biological Invasions. _Global Change Biology_ <b>31</b>, e70144. <a href="https://doi.org/10.1111/gcb.70144" target="_blank">DOI: 10.1111/gcb.70144</a>


<br>
<p class="second"><u>2024</u></p>

<li>Schimdt, A.G., Anderson, I.M., <b>Bruel, R.</b>, Chapina, R.J., Doubek, J.P., Fiorini, S., Goldfard, S.K., Lacroix, G., Wander, H.L., Zigic, S., Stockwell, J.D. 2024. Impacts of hypoxia and planktivory on crustacean and rotifer diel vertical and horizontal migration behaviors. _Hydrobiologia_. <a href="https://link.springer.com/article/10.1007/s10750-024-05767-0" target="_blank">DOI: 10.1007/s10750-024-05767-0</a></li>

<li>Vagnon, C., Olden, J.D., Boulêtreau, S. <b>Bruel, R.</b>, Chevalier, M., Garcia, F., Holtgrieve, G., Jackson, M., Thebault, E., Tedeco, P.A., Cucherousset, J. 2024. Ecosystem synchrony: an emerging property to elucidate ecosystem responses to global change. _Trends in Ecology \& Evolution_. <a href="https://doi.org/10.1016/j.tree.2024.08.003" target="_blank">DOI: 10.1016/j.tree.2024.08.003</a></li>

<li>Lesser, J. S., <b>Bruel, R.</b>, Marcy-Quay, B., McReynolds, A. T., Stockwell, J. D., Marsden, J. E., 2024. Whole-lake food web model indicates alewife invasion fueled lake trout restoration and altered patterns of trophic flow Lake Champlain. _Journal of Great Lakes Research_. <a href="https://doi.org/10.1016/j.jglr.2023.102249" target="_blank">DOI: 10.1016/j.jglr.2023.102249</a></li>
 
<br>
<p class="second"><u>2023</u></p>


<li>Sharaf, N., Prats, J., Reynaud, N., Tormos, T., <b>Bruel, R.</b>, Peroux, T., Danis, P.A., 2023. A long-term dataset of simulated epilimnion and hypolimnion temperatures in 401 French lakes (1959–2020). _Earth System Science Data_, <b>15</b>, 5631–5650. <a href="https://essd.copernicus.org/articles/15/5631/2023/" target="_blank">DOI: 10.5194/essd-15-5631-2023</a></li>

<li>Frossard, V., Sabatier, P., <b>Bruel, R.</b>, Vagnon, C., Tissot, N., Curt-Grand-Gaudin, N., Perga, M.-E., 2023. Intense touristic activities exceed climate change to shape aquatic communities in a mountain lake. _Aquatic Sciences_ <b>85:71</b>. <a href="https://doi.org/10.1007/s00027-023-00968-6" target="_blank">DOI: 10.1007/s00027-023-00968-6</a></li>

<br>
<p class="second"><u>2021</u></p>
<li>Monchamp, M.-E., <b>Bruel, R.</b>, Frossard, V., McGowan, S., Lavrieux, M., Muschick, M., Perga, M.-E., Dubois, N., 2021. Paleoecological evidence for a multi-trophic regime shift in a perialpine lake (Lake Joux, Switzerland). _Anthropocene_ <b>35</b>: 100301<a href="https://www.sciencedirect.com/science/article/pii/S2213305421000242" target="_blank">DOI: 10.1016/j.ancene.2021.100301</a></li>

<li><b>Bruel, R.</b>, Marsden, J. E., Pientka, B., Staats, N., Mihuc, T., Stockwell, J. D., 2021. Rainbow smelt population responses to species invasions and change in environmental condition. _Journal of Great Lakes Research_ <b>47*(4)*</b>: 1171-1181. <a href="https://www.sciencedirect.com/science/article/pii/S0380133021000927" target="_blank">DOI: 10.1016/j.jglr.2021.04.008</a></li>

<li>Rantala, M. V., <b>Bruel, R.</b>, Marchetto, A., Lami, A., Spangenberg, J., Perga, M.-E., 2021. Heterogeneous responses of lake CO2 to nutrients and warming in perialpine lakes imprinted in subfossil cladoceran &#948;13C values. _Science of the Total Environment_ <b>782</b>: 146923. <a href="https://www.sciencedirect.com/science/article/pii/S0048969721019938" target="_blank">DOI: 10.1016/j.scitotenv.2021.146923</a></li>

<li><b>Bruel, R.</b>, Girardclos, S., Marchetto, A., Kremer, K., Crouzet, C., Reyss, J.-L., Sabatier, P., Perga, M.-E., 2021. Reframing Lake Geneva ecological trajectory in a context of multiple but asynchronous pressures. _Journal of Paleolimnology_. <b>65*(3)*</b>: 353-368 <a href="https://www.researchgate.net/publication/348815775_Reframing_Lake_Geneva_ecological_trajectory_in_a_context_of_multiple_but_asynchronous_pressures" target="_blank">DOI: 10.1007/s10933-021-00176-y</a></li>

<li><b>Bruel, R.</b>, White, E. R., 2021. Sampling requirements and approaches to detect ecosystem shifts. _Ecological Indicators_. <b>121</b>: 107096 <a href="https://authors.elsevier.com/sd/article/S1470-160X(20)31035-9" target="_blank">DOI: 10.1016/j.ecolind.2020.107096</a></li>

<br>
<p class="second"><u>2020</u></p>
<li><b>Bruel, R.</b>, Sabatier, P., 2020. serac: a R package for ShortlivEd RAdionuclide Chronology of recent sediment cores. _Journal of Environmental Radioactivity_ <b>225</b>. <a href="https://www.sciencedirect.com/science/article/abs/pii/S0265931X20306950" target="_blank">DOI: 10.1016/j.jenvrad.2020.106449</a></li>

<br>
<p class="second"><u>2018</u></p>
<li>Hamilton, R., Brussel, T., Asena, Q., <b>Bruel, R.</b>, Marcisz, K., Słowiński, M., Morris, J., 2018. Assessing the links between resilience, disturbance and functional traits in paleoecological datasets. _Past Global Change Magazine_ <a href="https://www.pastglobalchanges.org/publications/pages-magazines/pages-magazine/12733" target="_blank">DOI: 10.22498/pages.26.2.87</a> </li>

<li>Perga, M.-E., <b>Bruel, R.</b>, Rodriguez, L., Guénand, Y., Bouffard, D., 2018. Storm impacts on alpine lakes: antecedent weather conditions matter more than the event intensity. _Global Change Biology_ <b>24*(10)*</b>: 5004-5016. <a href="https://doi.org/10.1111/gcb.14384" target="_blank"> DOI: 10.1111/gcb.14384</a>
&nbsp;&nbsp;&nbsp;&nbsp;</li>

<li><b>Bruel, R.</b>, Marchetto, A., Bernard, A., Lami, A., Sabatier, P., Frossard, V., Perga, M.-E., 2018. Seeking alternative stable states in a deep lake. _Freshwater Biology_ <b>63*(6)*</b>: 553-568. <a href="https://doi.org/10.1111/fwb.13093" target="_blank">DOI: 10.1111/fwb.13093 </a><br></li>
</ol>


<br>
<head><b>Preprints: (*published)</b></head>
&nbsp;&nbsp;&nbsp;&nbsp;


<ol reversed>
<li><b>*Bruel, R.</b>, Marsden, J. E., Pientka, B., Staats, N., Mihuc, T., Stockwell, J. D., 2020. Rainbow smelt population responses to species invasions and change in environmental condition. _bioRxiv_. <a href="https://www.biorxiv.org/content/10.1101/2020.10.08.332205v1">DOI: 10.1101/2020.10.08.332205</a></li>

<li><b>*Bruel, R.</b>, White, E. R., 2020. Sampling requirements and approaches to detect ecosystem shifts. _bioRxiv_. <a href="https://www.biorxiv.org/content/10.1101/2020.04.07.030643v1">DOI: 10.1101/2020.04.07.030643 </a></li>

<li><b>*Bruel, R.</b>, Sabatier, P., 2020. serac: a R package for ShortlivEd RAdionuclide Chronology of recent sediment cores. _earthaRxiv_. <a href="https://eartharxiv.org/repository/view/461/">DOI: 10.31223/osf.io/f4yma</a></li>

<li><b>*Bruel, R.</b>, Girardclos, S., Marchetto, A., Kremer, K., Crouzet, C., Reyss, J.-L., Sabatier, P., Perga, M.-E., 2019. Reframing Lake Geneva ecological trajectory in a context of multiple but asynchronous stressors _earthaRxiv_. <a href="https://eartharxiv.org/repository/view/510/ ">DOI: 10.31223/osf.io/j8up3</a></li>

<br/>

