---
#title: "software"
#author: "Rosalie Bruel"
#date: "19/02/2019"
output: html_document
---

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134870808-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-134870808-1');
</script>


______

When I first used R, I would have never thought I would like it that much (heard that before?). I do most of my work in R because I don't have any limitation in term of analyses, and it grants reproducibility of my results. I am also very reluctant to use any software that is not freely available, because it limits potential collaboration.
My GitHub gathers some of my past and current projects. While you're here, have a look at:

* The code to reproduce the analyses from our paper <a href="https://www.researchgate.net/publication/323394346_Seeking_alternative_stable_states_in_a_deep_lake" target="_blank">'Seeking alternative stable states in a deep lake'</a> is available <a href="https://github.com/rosalieb/AltStableStates" target="_blank">here</a>.
* Our package <a href="https://github.com/rosalieb/serac" target="_blank">_serac_</a>,  just got accepted in Journal of Environmental Radioactivity. <a href="https://eartharxiv.org/f4yma/">Link to the preprint</a> (DOI: 10.31223/osf.io/f4yma).
* The code to reproduce this website is on my GitHub as well, <a href="https://github.com/rosalieb/rosaliebruelweb" target="_blank">here</a>. I used <a href="https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html">Emily C. Zabor's tutorial</a>.